//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBIT_Application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eBITEntities1 : DbContext
    {
        public eBITEntities1()
            : base("name=eBITEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<product_category> product_categories { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
